services:
  db:
    image: ankane/pgvector:latest
    container_name: nexus_db
    restart: always
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ubuntu
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: nexus_app
    ports:
      - "3400:3400"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: